<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rahel Häusler">
<meta name="dcterms.date" content="2024-04-10">

<title>P1-6-Haeusler</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="P1-6-Haeusler_files/libs/clipboard/clipboard.min.js"></script>
<script src="P1-6-Haeusler_files/libs/quarto-html/quarto.js"></script>
<script src="P1-6-Haeusler_files/libs/quarto-html/popper.min.js"></script>
<script src="P1-6-Haeusler_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="P1-6-Haeusler_files/libs/quarto-html/anchor.min.js"></script>
<link href="P1-6-Haeusler_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="P1-6-Haeusler_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="P1-6-Haeusler_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="P1-6-Haeusler_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="P1-6-Haeusler_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries">Preliminaries</a></li>
  <li><a href="#task-1" id="toc-task-1" class="nav-link" data-scroll-target="#task-1">Task 1</a>
  <ul>
  <li><a href="#task-description" id="toc-task-description" class="nav-link" data-scroll-target="#task-description">Task Description</a></li>
  </ul></li>
  <li><a href="#task-2" id="toc-task-2" class="nav-link" data-scroll-target="#task-2">Task 2</a>
  <ul>
  <li><a href="#task-description-1" id="toc-task-description-1" class="nav-link" data-scroll-target="#task-description-1">Task Description</a>
  <ul class="collapse">
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#inq_last_6mths" id="toc-inq_last_6mths" class="nav-link" data-scroll-target="#inq_last_6mths">inq_last_6mths</a></li>
  <li><a href="#pub_rec" id="toc-pub_rec" class="nav-link" data-scroll-target="#pub_rec">pub_rec</a></li>
  <li><a href="#revol_bal" id="toc-revol_bal" class="nav-link" data-scroll-target="#revol_bal">revol_bal</a></li>
  <li><a href="#dti" id="toc-dti" class="nav-link" data-scroll-target="#dti">dti</a></li>
  <li><a href="#home_ownership" id="toc-home_ownership" class="nav-link" data-scroll-target="#home_ownership">home_ownership</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#further-exploration" id="toc-further-exploration" class="nav-link" data-scroll-target="#further-exploration">Further Exploration</a></li>
  </ul></li>
  <li><a href="#task-3" id="toc-task-3" class="nav-link" data-scroll-target="#task-3">Task 3</a>
  <ul>
  <li><a href="#task-description-2" id="toc-task-description-2" class="nav-link" data-scroll-target="#task-description-2">Task Description:</a>
  <ul class="collapse">
  <li><a href="#analysis-1" id="toc-analysis-1" class="nav-link" data-scroll-target="#analysis-1">Analysis</a>
  <ul class="collapse">
  <li><a href="#inq_last_6mths-1" id="toc-inq_last_6mths-1" class="nav-link" data-scroll-target="#inq_last_6mths-1">inq_last_6mths</a></li>
  <li><a href="#pub_rec-1" id="toc-pub_rec-1" class="nav-link" data-scroll-target="#pub_rec-1">pub_rec</a></li>
  <li><a href="#revol_bal-1" id="toc-revol_bal-1" class="nav-link" data-scroll-target="#revol_bal-1">revol_bal</a></li>
  <li><a href="#dti-1" id="toc-dti-1" class="nav-link" data-scroll-target="#dti-1">dti</a></li>
  <li><a href="#home_ownership-1" id="toc-home_ownership-1" class="nav-link" data-scroll-target="#home_ownership-1">home_ownership</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  <li><a href="#task-4" id="toc-task-4" class="nav-link" data-scroll-target="#task-4">Task 4</a>
  <ul>
  <li><a href="#task-description-3" id="toc-task-description-3" class="nav-link" data-scroll-target="#task-description-3">Task Description:</a></li>
  <li><a href="#further-exploration-1" id="toc-further-exploration-1" class="nav-link" data-scroll-target="#further-exploration-1">Further Exploration</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">P1-6-Haeusler</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rahel Häusler </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="preliminaries" class="level2">
<h2 class="anchored" data-anchor-id="preliminaries">Preliminaries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("quarto")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("data.table")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr")</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quarto)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>LCdata <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"LCdata.csv"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">6</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>myLCdata <span class="ot">&lt;-</span> LCdata <span class="sc">%&gt;%</span> <span class="fu">sample</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">slice_sample</span>(<span class="at">prop =</span> .<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-1" class="level1">
<h1>Task 1</h1>
<section id="task-description" class="level2">
<h2 class="anchored" data-anchor-id="task-description">Task Description</h2>
<p>Use dplyr::glimpse() and str() to get a first impression of your data set. Download the data dictionary from Moodle, find the attributes that are present in your data set myLCdata and read the corresponding descriptions. Try to understand their meaning in the context of peer-to-peer (P2P) loans.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a glimpse of the dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(myLCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 44,369
Columns: 5
$ inq_last_6mths &lt;int&gt; 0, 1, 0, 2, 0, 4, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1…
$ pub_rec        &lt;int&gt; 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0…
$ revol_bal      &lt;int&gt; 474, 41023, 16683, 15080, 17747, 84447, 6489, 46750, 26…
$ dti            &lt;dbl&gt; 10.43, 15.73, 12.37, 19.64, 14.06, 39.16, 13.79, 9.09, …
$ home_ownership &lt;chr&gt; "RENT", "RENT", "RENT", "MORTGAGE", "MORTGAGE", "RENT",…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use str() function to get structure of the dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(myLCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  44369 obs. of  5 variables:
 $ inq_last_6mths: int  0 1 0 2 0 4 1 0 0 0 ...
 $ pub_rec       : int  0 0 0 0 2 0 0 0 1 0 ...
 $ revol_bal     : int  474 41023 16683 15080 17747 84447 6489 46750 2695 14157 ...
 $ dti           : num  10.4 15.7 12.4 19.6 14.1 ...
 $ home_ownership: chr  "RENT" "RENT" "RENT" "MORTGAGE" ...</code></pre>
</div>
</div>
<table class="table">
<caption>Table 1: Extract of LC_DataDictionary</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 37%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Meaning for P2P Loans</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>inq_last_6mths</td>
<td>The number of inquiries in past 6 months (excluding auto and mortgage inquiries)</td>
<td>The number of inquiries helps the lender to evaluate the credit worthiness and credit trustiness of the borrower (e.g.&nbsp;may indicate overspending –&gt; risk of credit default)</td>
</tr>
<tr class="even">
<td>pub_rec</td>
<td>Number of derogatory public records</td>
<td>The number of derogatory public records helps the lender to assess the credit worthiness of the borrower. Furthermore, public records may be used for risk and compliance assessment of the borrower.</td>
</tr>
<tr class="odd">
<td>revol_bal</td>
<td>Total credit revolving balance.<br>
A revolving credit is a credit line that remains available even as you pay the balance. Borrowers can access credit up to a certain amount and then have ongoing access to that amount of credit. Typically a credit card</td>
<td>Revolving balance have to be considered in the creditworthiness assessment. The credit line has to be considered in the debit utilization ratio which influences the risk evaluation of the loan and therefore directly impacts the interest rate. Moreover, the credit revolving balance can help to understand the financial stability of the borrower.</td>
</tr>
<tr class="even">
<td>dti</td>
<td>A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations (excluding mortgage and the requested LC loan), divided by the borrower’s self-reported monthly income.</td>
<td>The dti is a measurement that helps lenders to assess the borrower’s ability to manage their debt payment relative to their income. It provides a measure of the borrower’s financial health and ability to repay their loan.</td>
</tr>
<tr class="odd">
<td>home_ownership</td>
<td>The home ownership status provided by the borrower during registration. Our values are: RENT, OWN, MORTGAGE, OTHER.</td>
<td>The home ownership status can provide insights into the financial stability and responsibility of the borrower.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="task-2" class="level1">
<h1>Task 2</h1>
<section id="task-description-1" class="level2">
<h2 class="anchored" data-anchor-id="task-description-1">Task Description</h2>
<p>Use summary() and skimr::skim() to review the main statistical metrics of your attributes. What do they tell you about the attributes? Interpret them not only statistically, but also in the domain context.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review main statistical metrics using summary()</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myLCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> inq_last_6mths       pub_rec          revol_bal            dti       
 Min.   : 0.0000   Min.   : 0.0000   Min.   :      0   Min.   : 0.00  
 1st Qu.: 0.0000   1st Qu.: 0.0000   1st Qu.:   6472   1st Qu.:11.91  
 Median : 0.0000   Median : 0.0000   Median :  11921   Median :17.61  
 Mean   : 0.6965   Mean   : 0.1973   Mean   :  16880   Mean   :18.14  
 3rd Qu.: 1.0000   3rd Qu.: 0.0000   3rd Qu.:  20772   3rd Qu.:23.95  
 Max.   :27.0000   Max.   :86.0000   Max.   :1630818   Max.   :64.50  
 NA's   :2         NA's   :2                                          
 home_ownership    
 Length:44369      
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
</div>
<div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review main statistical metrics using skim()</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(myLCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-skim-summary" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;1: Summary statistics for characters and numeric variables</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-skim-summary-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-skim-summary" style="flex-basis: 100.0%;justify-content: flex-start;">
<table class="table table-sm table-striped small">
<caption>(a) Data Summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">myLCdata</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">44369</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Key</td>
<td style="text-align: left;">NULL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><strong>Variable type: character</strong></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-skim-summary-2" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-skim-summary" style="flex-basis: 100.0%;justify-content: flex-start;">
<table class="table table-sm table-striped small">
<caption>(b) Summary of character variables</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">home_ownership</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><strong>Variable type: numeric</strong></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-skim-summary-3" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-skim-summary" style="flex-basis: 100.0%;justify-content: flex-start;">
<table class="table table-sm table-striped small">
<caption>(c) Summary of numeric variables</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">inq_last_6mths</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">pub_rec</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">86.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">revol_bal</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">16879.65</td>
<td style="text-align: right;">22143.45</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6472.00</td>
<td style="text-align: right;">11921.00</td>
<td style="text-align: right;">20772.00</td>
<td style="text-align: right;">1630818.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">dti</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.14</td>
<td style="text-align: right;">8.32</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">11.91</td>
<td style="text-align: right;">17.61</td>
<td style="text-align: right;">23.95</td>
<td style="text-align: right;">64.5</td>
<td style="text-align: left;">▅▇▃▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<section id="inq_last_6mths" class="level4">
<h4 class="anchored" data-anchor-id="inq_last_6mths">inq_last_6mths</h4>
<p>With the mean being at 0.6965 for the number of inquiries in the last 6 months, it is to assume that the majority requests a loan for the first time in the last 6 months. Considering the median of 0.00 and the maximum value of 27, it is to say that the distribution is right-skewed. Furthermore to highlight is the aspect, that 75% of the loan request in the last 6 months are either their first or second request. For two observations, the number of inquiries in the last 6 months are missing. However, this small number does not hinder the analysis of the data set. The number of inquiries may give an indication on how urgent the requester needs the credit and may indicate financial difficulties of the requester. As for example the observation with 27 counts of inquires in the last 6 months would lead to believe, that the requester is in a more financial turbulence than the one with a first time request.</p>
</section>
<section id="pub_rec" class="level4">
<h4 class="anchored" data-anchor-id="pub_rec">pub_rec</h4>
<p>For the number of public records, it is interesting to see that 75% of the observation have no registered public records (3rd quantile is at 0). With the mean being at 0.1973 and the maximum at 86.00, the distribution of the number of public records seems to be right-skewed. The observation with a number of public records of 86 can probably be considered as an outlier. For two observations, the number of inquiries in the last 6 months are missing. However, the small number seems not to be relevant for the further analysis of the data set. People with either a high number of public records or a severe entry in the public records may not receive credits from financial institute due to compliance reasons. For people with no public records, a credit taken out from the lending club could be more interesting in regard to the interest rate.</p>
</section>
<section id="revol_bal" class="level4">
<h4 class="anchored" data-anchor-id="revol_bal">revol_bal</h4>
<p>For the attribute revolving balance, as the median is smaller as the mean, it can be said that it is right-skewed as well. The maximum amount of 1’630’818 seems to be a very high amount with the second highest amount being at 952’013. It may seem that those high values are outliers. However, it is essential to further analyse these observation and to determine, if these are erroneous input or not.</p>
</section>
<section id="dti" class="level4">
<h4 class="anchored" data-anchor-id="dti">dti</h4>
<p>As the other previous mentioned values, the attribute debt-to-income seems to be right-skewed as well as the median is smaller than the mean and the maximum value is at 64.50. With the 3rd quantile being at 23.95, the majority of the observation have debt-to-income ratio below 25%. As mortgages and the requested LC loan is not considered in this calculation, it is difficult to assess the real “credit risk” of the observation as their financial obligation may be much higher than expected.</p>
</section>
<section id="home_ownership" class="level4">
<h4 class="anchored" data-anchor-id="home_ownership">home_ownership</h4>
<p>As the attribute home_ownership is categorical, the calculation of a mean, median etc. is not possible. The attribute home ownership may give an indication about the financial stability and back ups of the requester. An exploration of the distribution will be done in the further steps with an histogram. Additionally, you will find the an insight of the distribution of this attribute in the following section “Further Exploration”. 50% of the observation have a mortgage on their own property and almost 40% are currently renting. As owning a property and renting a property are the most common living situation nowadays, the data set seems not to be unbalanced. Furthermore, as neither mortgage payments as well as the rent payments are considered in the debt-to-income ratio, this attribute may get a further insight on the financial obligation of the requester. Additionally, as can be seen in the further exploration, for the attribute home_ownership, two additional variables, “NONE”and “ANY”, appear in the data set. These two are not mentioned in the description of the attribute.</p>
</section>
</section>
</section>
<section id="further-exploration" class="level2">
<h2 class="anchored" data-anchor-id="further-exploration">Further Exploration</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get unique values of home_ownership</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>unique_values <span class="ot">&lt;-</span> <span class="fu">unique</span>(myLCdata<span class="sc">$</span>home_ownership)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty data frame to store the results</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>result_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Home_Ownership =</span> <span class="fu">character</span>(), <span class="at">Count =</span> <span class="fu">integer</span>(), <span class="at">Percentage =</span> <span class="fu">numeric</span>(), <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each unique value</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (value <span class="cf">in</span> unique_values) {</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Count occurrences of the value</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  count <span class="ot">&lt;-</span> <span class="fu">sum</span>(myLCdata<span class="sc">$</span>home_ownership <span class="sc">==</span> value)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate percentage and round to two decimal places</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  percentage <span class="ot">&lt;-</span> <span class="fu">round</span>((count <span class="sc">/</span> <span class="fu">nrow</span>(myLCdata)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Append to the result data frame</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  result_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(result_df, <span class="fu">data.frame</span>(<span class="at">Home_Ownership =</span> value, <span class="at">Count =</span> count, <span class="at">Percentage =</span> percentage))</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result data frame</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Home_Ownership Count Percentage
1           RENT 17697      39.89
2       MORTGAGE 22272      50.20
3          OTHER    14       0.03
4            OWN  4382       9.88
5           NONE     3       0.01
6            ANY     1       0.00</code></pre>
</div>
</div>
</section>
</section>
<section id="task-3" class="level1">
<h1>Task 3</h1>
<section id="task-description-2" class="level2">
<h2 class="anchored" data-anchor-id="task-description-2">Task Description:</h2>
<p>Choose at least one suitable diagram type (e.g.&nbsp;a histogram, a scatterplot) for each of the 5 attributes in your data set and visualize it using ggplot2. Give your plots a professional look (e.g., add a title, make the axes labels readable, add the measurement units if available).</p>
<p>Interpret each of your plots:</p>
<p>• What information can you read off the diagram type you chose (e.g.&nbsp;in a histogram you can read off range, distribution, etc.)?</p>
<p>• What does it tell you about the attribute in the context of the attribute semantic and domain? Does it confirm your first assumptions about the attribute from task 2?</p>
<section id="analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="analysis-1">Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the xlim range</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>xlim_range <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">8</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the data to count the number of values outside the xlim range</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>values_outside_range <span class="ot">&lt;-</span> myLCdata<span class="sc">$</span>inq_last_6m[myLCdata<span class="sc">$</span>inq_last_6m <span class="sc">&lt;</span> xlim_range[<span class="dv">1</span>] <span class="sc">|</span> myLCdata<span class="sc">$</span>inq_last_6m <span class="sc">&gt;</span> xlim_range[<span class="dv">2</span>]]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of values outside the xlim range</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>num_outside_range <span class="ot">&lt;-</span> <span class="fu">length</span>(values_outside_range)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the histogram with the specified xlim range</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(myLCdata<span class="sc">$</span>inq_last_6m,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of Inquiries in Last 6 Months"</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of Inquiries"</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> xlim_range,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Number of values outside xlim range:"</span>, num_outside_range))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Hist_inq_last_6mth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Hist_inq_last_6mth-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Histogram showing the distribution of the attribute inq_last_6mth</figcaption>
</figure>
</div>
</div>
</div>
<section id="inq_last_6mths-1" class="level4">
<h4 class="anchored" data-anchor-id="inq_last_6mths-1">inq_last_6mths</h4>
<p>For the number of inquiries in the last 6 months, the assumption done in task 2 can be confirmed as the majority of observations lies between 0 up to 2 inquiries. Only a small number of observation have more than 2 inquiries in the last 6 months. As the range of the number of inquires has been limited to 8, 7 observations are not visualized in the histogram. <a href="#fig-Hist_inq_last_6mth">Figure&nbsp;1</a> may indicate that either the first or second inquiry is successful and therefore, not an additional one is done. Or, that the majority of people who are interested in a loan form LC consider other financing possibilities after 2 denied requests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of missing values in pub_rec</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>num_missing <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(myLCdata<span class="sc">$</span>pub_rec))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of values exceeding the limit</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>num_exceeding_limit <span class="ot">&lt;-</span> <span class="fu">sum</span>(myLCdata<span class="sc">$</span>pub_rec <span class="sc">&gt;</span> <span class="dv">9</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a frequency distribution with binwidth=1 for pub_rec</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(myLCdata, <span class="fu">aes</span>(<span class="at">x =</span> pub_rec)) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Frequency Distribution of Public Records"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Public Records"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Number of missing values:"</span>, num_missing,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"</span><span class="sc">\n</span><span class="st">Number of values outside X range:"</span>, num_exceeding_limit)) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">9</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a> <span class="co"># coord_cartesian(ylim = c(0, 7500))+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Hist_pub_rec" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Hist_pub_rec-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Histogram showing the distribution of the attribute pub_rec</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="pub_rec-1" class="level4">
<h4 class="anchored" data-anchor-id="pub_rec-1">pub_rec</h4>
<p>For the number of public records, the analysis conducted in task 2 can be confirmed as well the majority of the observation has no public records. Furthermore, a much smaller number of observations have 1 public record and a even smaller number have more than 2 public records. For the visualization, the number of pubic records display have been limited to 9. This leads to 6 observation not being visualized. <a href="#fig-Hist_pub_rec">Figure&nbsp;2</a> supports the assumptions that especially law-abiding people are requesting loans at the Lenders Club. This may be influenced by the fact, that borrowers with no or a small number of public records, probably depending as well on which entry, receive an interesting interest rate. Furthermore, lenders may be more willing to lend their money to someone with a low number of public records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of values exceeding the limit</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>num_exceeding_limit_revolbal <span class="ot">&lt;-</span> <span class="fu">sum</span>(myLCdata<span class="sc">$</span>revol_bal <span class="sc">&gt;</span> <span class="dv">300000</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram for revol_bal</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(myLCdata<span class="sc">$</span>revol_bal,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of total credit revolving balance"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Total credit revolving balance"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">300000</span>),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Number of values outside X range:"</span>, num_exceeding_limit_revolbal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Hist_revol_bal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Hist_revol_bal-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Histogram showing the distribution of the attribute revol_bal</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="revol_bal-1" class="level4">
<h4 class="anchored" data-anchor-id="revol_bal-1">revol_bal</h4>
<p>For the visualization of the credit revolving balance, the amount of balances has been limited to USD 300’000, leading to 19 observation not being displayed. The assumption of a right-skewed distribution seems to be correct. Additionally, it is visible that the majority of observation have a revolving balance between USD 0 and USD 100’000. You may interpret the result that observation with an revolving balance over USD 100’000 are not ordinary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram for dti</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(myLCdata<span class="sc">$</span>dti,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of Debt-to-Income Ratio (dti)"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Debt-to-Income Ratio (dti)"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Hist_dti" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Hist_dti-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Histogram showing the distribution of the attribute dti</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a boxplot for dti</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(myLCdata<span class="sc">$</span>dti,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot of Debt-to-Income Ratio (dti)"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Debt-to-Income Ratio (dti)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BP_dti" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-BP_dti-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Boxplot showing the distribution of the attribute dti</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="dti-1" class="level4">
<h4 class="anchored" data-anchor-id="dti-1">dti</h4>
<p>The box plot diagram confirms the calculated median of 18.14 from Task 2. Furthermore, you can well see 4 outlier observations which are depicted as dots in <a href="#fig-BP_dti">Figure&nbsp;5</a>. Additionally, in <a href="#fig-Hist_dti">Figure&nbsp;4</a>, the main observations have a debt-to-income ratio between 0 to 40 . Between those two numbers, the distribution looks similar to an univariate distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert home_ownership to factor </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>myLCdata<span class="sc">$</span>home_ownership <span class="ot">&lt;-</span> <span class="fu">factor</span>(myLCdata<span class="sc">$</span>home_ownership, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"RENT"</span>, <span class="st">"OWN"</span>, <span class="st">"MORTGAGE"</span>, <span class="st">"OTHER"</span>, <span class="st">"ANY"</span>, <span class="st">"NONE"</span>))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the frequency count of each category</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>frequency <span class="ot">&lt;-</span> <span class="fu">table</span>(myLCdata<span class="sc">$</span>home_ownership)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for home_ownership</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(frequency,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">main =</span> <span class="st">"Frequency of Home Ownership"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">xlab =</span> <span class="st">"Home Ownership"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(frequency) <span class="sc">*</span> <span class="fl">1.2</span>))  <span class="co"># Adjust the y-axis limit</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add text labels for numeric values</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> bp,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> frequency <span class="sc">+</span> <span class="dv">1</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> frequency,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">pos =</span> <span class="dv">3</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Hist_home_ownership" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Hist_home_ownership-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Histogram showing the distribution of the attribute home_ownership</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="home_ownership-1" class="level4">
<h4 class="anchored" data-anchor-id="home_ownership-1">home_ownership</h4>
<p>The histogram of the variable “home_ownership” confirms the calculated distribution in percentage of Task 2. The two categories “Mortgage” and “Rent” are the most common ones, which are as well the most common living situation in considering today’s society.</p>
</section>
</section>
</section>
</section>
<section id="task-4" class="level1">
<h1>Task 4</h1>
<section id="task-description-3" class="level2">
<h2 class="anchored" data-anchor-id="task-description-3">Task Description:</h2>
<p>In task 3, you looked at each variable separately. Now the goal is to see if there are some obvious correlations or patterns when looking at pairs of variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>myLCdata_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(myLCdata[, <span class="fu">c</span>(<span class="st">"inq_last_6mths"</span>, <span class="st">"pub_rec"</span>, <span class="st">"revol_bal"</span>, <span class="st">"dti"</span>, <span class="st">"home_ownership"</span>)])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ggpairs(myLCdata_clean)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>({</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(myLCdata_clean[, <span class="fu">c</span>(<span class="st">"inq_last_6mths"</span>, <span class="st">"pub_rec"</span>, <span class="st">"revol_bal"</span>, <span class="st">"dti"</span>, <span class="st">"home_ownership"</span>)])</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Correlation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-Correlation-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Visualization of possible correlation of two attributes</figcaption>
</figure>
</div>
</div>
</div>
<p>As I couldn’t find a visible correlation in the previously produced Figure, <a href="#fig-Correlation">Figure&nbsp;7</a>, I tried to calculate the correlation of each set of two variables in the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the names of numeric columns</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>numeric_columns <span class="ot">&lt;-</span> <span class="fu">names</span>(myLCdata)[<span class="fu">sapply</span>(myLCdata, is.numeric)]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset myLCdata using the numeric column names</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>numeric_data <span class="ot">&lt;-</span> myLCdata[, ..numeric_columns]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove missing values</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>numeric_data_noNA <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(numeric_data)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert data frame to matrix-like object</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>numeric_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(numeric_data_noNA)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation matrix</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_matrix)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert correlation matrix to data frame</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>correlation_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(correlation_matrix)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the correlation matrix as a table</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(correlation_df, <span class="at">caption =</span> <span class="st">"Correlation Matrix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-corr_matr" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2: Table of the Correlation</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">inq_last_6mths</th>
<th style="text-align: right;">pub_rec</th>
<th style="text-align: right;">revol_bal</th>
<th style="text-align: right;">dti</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">inq_last_6mths</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.0494919</td>
<td style="text-align: right;">-0.0081095</td>
<td style="text-align: right;">-0.0134143</td>
</tr>
<tr class="even">
<td style="text-align: left;">pub_rec</td>
<td style="text-align: right;">0.0494919</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.0876492</td>
<td style="text-align: right;">-0.0351558</td>
</tr>
<tr class="odd">
<td style="text-align: left;">revol_bal</td>
<td style="text-align: right;">-0.0081095</td>
<td style="text-align: right;">-0.0876492</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.1411285</td>
</tr>
<tr class="even">
<td style="text-align: left;">dti</td>
<td style="text-align: right;">-0.0134143</td>
<td style="text-align: right;">-0.0351558</td>
<td style="text-align: right;">0.1411285</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>After further clarification with Gwen, I decided to further investigate the relationship of the two variables revol_bal and home_ownership, as can be seen in <a href="#fig-BP_T4_11">Figure&nbsp;8</a>. Before running the code, I expected to see a difference between home owners, either with or without mortgage, and people who are currently renting. I expected this result as I thought that home owners either have invested their assets in their homes and / or have more financial obligations due to mortgage payments, both leading to a more stressed financial situation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot of revol_bal grouped by home_ownership</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(revol_bal <span class="sc">~</span> home_ownership, <span class="at">data =</span> myLCdata,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot of Revolving Balance by Home Ownership"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Home Ownership"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Revolving Balance"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"skyblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BP_T4_11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-BP_T4_11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;8: Boxplotof the two attribute revol_bal and home_ownership</figcaption>
</figure>
</div>
</div>
</div>
<p>Considering <a href="#fig-BP_T4_11">Figure&nbsp;8</a>, a small difference between people owning a property, either with or without mortgage, and people who are renting can be seen. Furthermore, the observations with the home ownership status “Mortgage” tend to have a higher Revolving Balance. This may be due to more financial obligations due to the mortgage payment. Therefore, people may request a higher revolving balance (resp. a higher credit card limit) so they are able to pay their daily bills.</p>
<p>In the next step, I wanted to analysis if there is a visible difference between the home ownership status and the number of public records. My first assumption is that people who live in their own property have a smaller number of public record entries as they may have more stability in their life.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot of revol_bal grouped by home_ownership</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(pub_rec <span class="sc">~</span> home_ownership, <span class="at">data =</span> myLCdata,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot of Public Records by Home Ownership"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Home Ownership"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Public Records"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"skyblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BP_T4_13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-BP_T4_13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Boxplotof the two attribute pub_rec and home_ownership</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot of pub_rec grouped by home_ownership</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(pub_rec <span class="sc">~</span> home_ownership, <span class="at">data =</span> myLCdata,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot of Public Records by Home Ownership"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Home Ownership"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Public Records"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">40</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BP_T4_14" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-BP_T4_14-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Zoomed in Boxplotof the two attribute pub_rec and home_ownership</figcaption>
</figure>
</div>
</div>
</div>
<p>However, as shown in <a href="#fig-BP_T4_13">Figure&nbsp;9</a> and <a href="#fig-BP_T4_14">Figure&nbsp;10</a>, no significant difference can be detected. Only the number of the outliers may differ. However, as outliers are observation which vary greatly from the other observations, these points will not be considered for comparison.</p>
<p>Additionally, I wanted to further explore the relationship between the two attributes debt-to-income and revolving balance. As described in task 1, dti considers the total monthly debt payments on the total debt obligations in its calculation. However, as described in the LC Data Dictionary, the revolving balance is typically the credit card. As the payment system in the US varies from the one in Switzerland, it is difficult to understand how the “open” revolving balance would be considered in the debt-to-income ratio. In my understanding, people with a high income are more likely to get a high revolving balance granted. Nonetheless, the debt-to-income ratio should be remain in the same range.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between revol_bal and dti</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(myLCdata<span class="sc">$</span>revol_bal, myLCdata<span class="sc">$</span>dti)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of dti against revol_bal</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(myLCdata<span class="sc">$</span>dti, myLCdata<span class="sc">$</span>revol_bal,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatterplot of Debt-to-Income Ratio vs. Revolving Balance"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Debt-to-Income Ratio"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Revolving Balance"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add correlation coefficient to the plot</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">min</span>(myLCdata<span class="sc">$</span>dti), </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">max</span>(myLCdata<span class="sc">$</span>revol_bal),</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_T4_12" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_T4_12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;11: Scatterplot of the two attributes dti and revol_bal</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between revol_bal and dti</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(myLCdata<span class="sc">$</span>revol_bal, myLCdata<span class="sc">$</span>dti)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of dti against revol_bal</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(myLCdata<span class="sc">$</span>dti, myLCdata<span class="sc">$</span>revol_bal,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatterplot of Debt-to-Income Ratio vs. Revolving Balance"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Debt-to-Income Ratio"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Revolving Balance"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">200000</span>))</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Add correlation coefficient to the plot</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">min</span>(myLCdata<span class="sc">$</span>dti), </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">max</span>(myLCdata<span class="sc">$</span>revol_bal),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_T4_121" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_T4_121-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Zoomed in Scatterplot of the two attributes dti and revol_bal</figcaption>
</figure>
</div>
</div>
</div>
<p>As can be seen in <a href="#fig-SP_T4_12">Figure&nbsp;11</a> as well in <a href="#fig-SP_T4_121">Figure&nbsp;12</a>, it looks like the amount of the revolving balance seems is limited to a 40% Debt-to-Income Ratio. Only four observations have been done outside the mentioned 40% limit. As I do not have the data on the income, the analysis of the relationship between the income and the height of the revolving balance cannot be done. However, it can be said that in all cases, besides the outliers, the revolving balance seems to be limited to 40% debt-to-income ratio.</p>
<p>In a further step, I wanted to investigate, if any further insights could be gained by adding the attribute home_ownership in the visualization of the attributes revol_bal and dti. As already known from <a href="#fig-BP_T4_11">Figure&nbsp;8</a>, home owners with a mortgage tend to have a higher revolving balance. Considering that factor, I would expect that the debt-to-income ratio for home owners with a mortgage would be higher than the one for the observations with the home owner status “Rent”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between revol_bal and dti</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(myLCdata<span class="sc">$</span>revol_bal, myLCdata<span class="sc">$</span>dti)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of dti against revol_bal with home_ownership as color</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(myLCdata, <span class="fu">aes</span>(<span class="at">x =</span> dti, <span class="at">y =</span> revol_bal, <span class="at">color =</span> home_ownership)) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Debt-to-Income Ratio vs. Revolving Balance"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Debt-to-Income Ratio"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Revolving Balance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_T4_21" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_T4_21-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;13: Scatterplot showing the distribution of the attribute revol_bal, dti and home_ownership</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-SP_T4_21">Figure&nbsp;13</a>, observations with the home owner status “Mortgage” have in general a higher revolving balance than observation with the home owner status “Rent”. This disparity could be due to the increased financial obligations associated with mortgage payments. Depending on the time frame in which the data was collected, this may indicate a trend for home owners with mortgages to maintain a higher revolving balance to cover their daily expenses. However, no further insights can be gained by considering the attribute debt-to income-ratio. Additionally, observations with the home owner status “Own” seems to be more distributed and therefore, it is more difficult to recognize a trend.</p>
</section>
<section id="further-exploration-1" class="level2">
<h2 class="anchored" data-anchor-id="further-exploration-1">Further Exploration</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude rows with missing values in dti and inq_last_6mths</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">complete.cases</span>(myLCdata<span class="sc">$</span>dti, myLCdata<span class="sc">$</span>inq_last_6mths)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>dti <span class="ot">&lt;-</span> myLCdata<span class="sc">$</span>dti[complete_cases]</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>inq_last_6mths <span class="ot">&lt;-</span> myLCdata<span class="sc">$</span>inq_last_6mths[complete_cases]</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between dti and inq_last_6mths</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>correlation_3 <span class="ot">&lt;-</span> <span class="fu">cor</span>(dti, inq_last_6mths)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of dti against inq_last_6mths</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(inq_last_6mths, dti,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatterplot of Debt-to-Income Ratio vs. Inquiries in Last 6 Months"</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation_3, <span class="dv">2</span>)),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Inquiries in Last 6 Months"</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Debt-to-Income Ratio"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_dti_inq_last_6mths" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_dti_inq_last_6mths-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;14: Scatterplot of the two attributes dti and inq_last_6mths</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude rows with missing values in inq_last_6mths and pub_rec</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">complete.cases</span>(myLCdata<span class="sc">$</span>inq_last_6mths, myLCdata<span class="sc">$</span>pub_rec)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>inq_last_6mths <span class="ot">&lt;-</span> myLCdata<span class="sc">$</span>inq_last_6mths[complete_cases]</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>pub_rec <span class="ot">&lt;-</span> myLCdata<span class="sc">$</span>pub_rec[complete_cases]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between inq_last_6mths and pub_rec</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>correlation_2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(inq_last_6mths, pub_rec)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of pub_rec against inq_last_6mths</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(inq_last_6mths, pub_rec,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatterplot of Inquiries in Last 6 Months vs. Public Records"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation_2, <span class="dv">2</span>)),</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Inquiries in Last 6 Months"</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Public Records"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_inq_last_6mths_pub_rec" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_inq_last_6mths_pub_rec-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;15: Histogram showing the distribution of the attribute revol_bal</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between pub_rec and dti</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(myLCdata<span class="sc">$</span>pub_rec, myLCdata<span class="sc">$</span>inq_last_6mths)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of inq_last_6mths against pub_rec with home_ownership as color</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(myLCdata, <span class="fu">aes</span>(<span class="at">x =</span> inq_last_6mths, <span class="at">y =</span> pub_rec, <span class="at">color =</span> home_ownership)) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Inquiries in the last 6 months vs. Public Recrods incl. status of home ownership "</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Inquiries in the last 6 months"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Public Records"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_T4_22" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_T4_22-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;16: Scatterplot showing the distribution of the attribute inq_last_6mths, pub_rec and home_ownership</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between pub_rec and dti</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(myLCdata<span class="sc">$</span>pub_rec, myLCdata<span class="sc">$</span>inq_last_6mths)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot of inq_last_6mths against pub_rec with home_ownership as color</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(myLCdata, <span class="fu">aes</span>(<span class="at">x =</span> inq_last_6mths, <span class="at">y =</span> pub_rec, <span class="at">color =</span> home_ownership)) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Inquiries in the last 6 months vs. Public Recrods incl. status of home ownership "</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Correlation ="</span>, <span class="fu">round</span>(correlation, <span class="dv">2</span>)),</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Inquiries in the last 6 months"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Public Records"</span>) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>)) <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SP_T4_221" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="P1-6-Haeusler_files/figure-html/fig-SP_T4_221-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;17: Zoomed in Scatterplot of Figure</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>